//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryStore.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stones()
        {
            this.Jewelries = new HashSet<Jewelries>();
        }
    
        public int IdStone { get; set; }
        public string NameStone { get; set; }
        public string ColorStone { get; set; }
        public float WeightStone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jewelries> Jewelries { get; set; }
    }
}
