//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryStore.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseItems
    {
        public int IdWarehouseItem { get; set; }
        public int IdWarehouse { get; set; }
        public int IdJewelry { get; set; }
        public int Quantity { get; set; }
    
        public virtual Jewelries Jewelries { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
